[package]
name = "winit-web-touch-event-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
web-sys = "0.3"

[patch.crates-io]
winit = { git = "https://github.com/ryo33/winit", rev = "0987b716e091f226f5fb1f3087314ea0ecd13c32" }
